/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.97
 * Generated at: 2026-03-14 15:02:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class file_005fuploader_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("<title>File Uploader</title>\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Grey+Qo&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("	\r\n");
      out.write("<!-- Bootstrap CSS -->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("body{\r\n");
      out.write("background:#f4f6f9;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Sidebar */\r\n");
      out.write(".sidebar{\r\n");
      out.write("height:100vh;\r\n");
      out.write("background:#343a40;\r\n");
      out.write("color:white;\r\n");
      out.write("position:fixed;\r\n");
      out.write("width:220px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar a{\r\n");
      out.write("color:white;\r\n");
      out.write("text-decoration:none;\r\n");
      out.write("display:block;\r\n");
      out.write("padding:12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar a:hover{\r\n");
      out.write("background:#495057;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Content */\r\n");
      out.write(".content{\r\n");
      out.write("margin-left:220px;\r\n");
      out.write("padding:20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Cards */\r\n");
      out.write(".card-box{\r\n");
      out.write("border-radius:10px;\r\n");
      out.write("color:white;\r\n");
      out.write("padding:20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bg-blue{background:#0d6efd;}\r\n");
      out.write(".bg-green{background:#198754;}\r\n");
      out.write(".bg-orange{background:#fd7e14;}\r\n");
      out.write(".bg-red{background:#dc3545;}\r\n");
      out.write("\r\n");
      out.write(".form-container{\r\n");
      out.write("max-width:600px;\r\n");
      out.write("margin:auto;\r\n");
      out.write("margin-top:60px;\r\n");
      out.write("padding:30px;\r\n");
      out.write("background:white;\r\n");
      out.write("border-radius:10px;\r\n");
      out.write("box-shadow:0 0 10px rgba(0,0,0,0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".upload-box{\r\n");
      out.write("max-width:500px;\r\n");
      out.write("margin:80px auto;\r\n");
      out.write("padding:30px;\r\n");
      out.write("background:white;\r\n");
      out.write("border-radius:10px;\r\n");
      out.write("box-shadow:0 0 10px rgba(0,0,0,0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* Mobile */\r\n");
      out.write("@media(max-width:768px){\r\n");
      out.write("\r\n");
      out.write(".sidebar{\r\n");
      out.write("position:relative;\r\n");
      out.write("width:100%;\r\n");
      out.write("height:auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".content{\r\n");
      out.write("margin-left:0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"sidebar\">\r\n");
      out.write("\r\n");
      out.write("<h4 class=\"text-center py-3\">Admin Panel</h4>\r\n");
      out.write("\r\n");
      out.write("<a href=\"dashboard.jsp\">Dashboard</a>\r\n");
      out.write("<a href=\"digital_invitation.jsp\">Digital Invitations</a>\r\n");
      out.write("<a href=\"interactive_invitation.jsp\">Interactive Invitations</a>\r\n");
      out.write("<a href=\"#\">File Uploder</a>\r\n");
      out.write("<a href=\"administrator.jsp\">Logout</a>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"content\">\r\n");
      out.write("\r\n");
      out.write("<!-- Navbar -->\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-light bg-white shadow-sm mb-4\">\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("<span class=\"navbar-brand\">File Uploader</span>\r\n");
      out.write("\r\n");
      out.write("<a href=\"administrator.jsp\" class=\"btn btn-outline-primary\">Logout</a>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" <!-- ----------------- Form starts here -->\r\n");
      out.write(" \r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"upload-box\">\r\n");
      out.write("\r\n");
      out.write("<h4 class=\"text-center mb-4\">Upload File</h4>\r\n");
      out.write("\r\n");
      out.write("<form action=\"uploadFile\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"mb-3\">\r\n");
      out.write("<label class=\"form-label\">Select File</label>\r\n");
      out.write("<input type=\"file\" name=\"file\" class=\"form-control\" required>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"d-grid\">\r\n");
      out.write("<button class=\"btn btn-primary\">Upload File</button>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write(" \r\n");
      out.write(" <!-- ------------------ Form ends here -->\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
