/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.97
 * Generated at: 2025-04-27 18:18:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import io.github.cdimascio.dotenv.Dotenv;
import io.github.cdimascio.dotenv.Dotenv;

public final class donate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("io.github.cdimascio.dotenv.Dotenv");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<script src=\"https://checkout.razorpay.com/v1/checkout.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("let xhttp=new XMLHttpRequest();\r\n");
      out.write("let RazorpayOrderId;\r\n");
      out.write("let url;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function CreateOrderId(nameReceived,emailReceived,mnoReceived){\r\n");
      out.write("	xhttp.open(\"GET\",url,false);\r\n");
      out.write("	xhttp.send();\r\n");
      out.write("	RazorpayOrderId=xhttp.responseText;\r\n");
      out.write("	OpenCheckout(nameReceived,emailReceived,mnoReceived);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function OpenCheckout(nameReceived,emailReceived,mnoReceived){\r\n");
      out.write("	var options = {\r\n");
      out.write("    \"key\": \"rzp_test_dtWFk2gzJrLE8s\", // Enter the Key ID generated from the Dashboard\r\n");
      out.write("    \"amount\": \"10000\", // Amount is in currency subunits. Default currency is INR. Hence, 50000 refers to 50000 paise\r\n");
      out.write("    \"currency\": \"INR\",\r\n");
      out.write("    \"name\": \"Acme Corp\",\r\n");
      out.write("    \"description\": \"Test Transaction\",\r\n");
      out.write("    \"image\": \"images/logo.jpg\",\r\n");
      out.write("    \"order_id\": RazorpayOrderId, //This is a sample Order ID. Pass the `id` obtained in the response of Step 1\r\n");
      out.write("    \"prefill\": {\r\n");
      out.write("        \"name\": nameReceived,\r\n");
      out.write("        \"email\":emailReceived,\r\n");
      out.write("        \"contact\": mnoReceived\r\n");
      out.write("    },\r\n");
      out.write("    \"notes\": {\r\n");
      out.write("        \"address\": \"Razorpay Corporate Office\"\r\n");
      out.write("    },\r\n");
      out.write("    \"theme\": {\r\n");
      out.write("        \"color\": \"#3399cc\"\r\n");
      out.write("    }\r\n");
      out.write("   };\r\n");
      out.write("var rzp1 = new Razorpay(options);\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("rzp1.on('payment.failed', function (response){\r\n");
      out.write("    alert(response.error.code);\r\n");
      out.write("    alert(response.error.description);\r\n");
      out.write("    alert(response.error.source);\r\n");
      out.write("    alert(response.error.step);\r\n");
      out.write("    alert(response.error.reason);\r\n");
      out.write("    alert(response.error.metadata.order_id);\r\n");
      out.write("    alert(response.error.metadata.payment_id);\r\n");
      out.write("    });\r\n");
      out.write("    rzp1.open();\r\n");
      out.write("    e.preventDefault();\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<title>Razorpay Java Integration</title>\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.min.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        *{\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            font-family: 'Noto Sans', sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("        body{\r\n");
      out.write("            background-color: #02042b;   \r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            margin: 0px;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("        }\r\n");
      out.write("        .container{\r\n");
      out.write("            background-color: #fff;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            width: 50%;\r\n");
      out.write("            max-width: 100%;\r\n");
      out.write("            margin: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        .header{\r\n");
      out.write("            background-color: #f7f7f7;\r\n");
      out.write("            border-bottom: 1px solid #f0f0f0;\r\n");
      out.write("            padding: 20px 40px;\r\n");
      out.write("        }\r\n");
      out.write("        .header h2{\r\n");
      out.write("            margin: 0;\r\n");
      out.write("        }\r\n");
      out.write("        .form{\r\n");
      out.write("            padding: 30px 40px;\r\n");
      out.write("        }\r\n");
      out.write("        .form-control{\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("            padding-bottom: 20px;\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("        .form-control label{\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            margin-bottom: 5px;\r\n");
      out.write("        }\r\n");
      out.write("        .form-control input{\r\n");
      out.write("            border: 2px solid #f0f0f0;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("            display: block;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding:10px;\r\n");
      out.write("            font-family: inherit;\r\n");
      out.write("        }\r\n");
      out.write("        .form-control.success input{\r\n");
      out.write("            border-color: #2ecc71;\r\n");
      out.write("        }\r\n");
      out.write("        .form-control.error input{\r\n");
      out.write("            border-color: #e74c3c;\r\n");
      out.write("        }\r\n");
      out.write("        .form-control.success i.fa-check-circle{\r\n");
      out.write("            visibility: visible;\r\n");
      out.write("            color: #2ecc71;\r\n");
      out.write("        }\r\n");
      out.write("        .form-control.error i.fa-exclamation-circle{\r\n");
      out.write("            visibility: visible;\r\n");
      out.write("            color: #e74c3c;\r\n");
      out.write("        }\r\n");
      out.write("        .form-control.error small{\r\n");
      out.write("            color: #e74c3c;\r\n");
      out.write("            visibility: visible;\r\n");
      out.write("        }\r\n");
      out.write("        .form-control i{\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 40px;\r\n");
      out.write("            right: 10px;\r\n");
      out.write("            visibility: hidden;\r\n");
      out.write("        }\r\n");
      out.write("        .form-control small{\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            bottom: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            visibility: hidden;\r\n");
      out.write("        }\r\n");
      out.write("        button{\r\n");
      out.write("            background-color:#2b84ea;\r\n");
      out.write("            border: 2px solid #2b84ea;\r\n");
      out.write("            border-radius: 50px;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            font-family: inherit;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            width: 50%;\r\n");
      out.write("            margin-left: 25%;\r\n");
      out.write("        }\r\n");
      out.write("        button:hover{\r\n");
      out.write("           color:white;\r\n");
      out.write("           background:#2ecc71;\r\n");
      out.write("           border:2px solid #2ecc71;\r\n");
      out.write("           cursor:pointer;\r\n");
      out.write("        } \r\n");
      out.write("      </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("        <div class=\"header\">\r\n");
      out.write("            <h2>Make a payment of Rs.100</h2>\r\n");
      out.write("        </div>\r\n");
      out.write("        <form class=\"form\" id=\"form\" autocomplete=\"off\">\r\n");
      out.write("            <div class=\"form-control\">\r\n");
      out.write("                <label for=\"\">Your Name</label>\r\n");
      out.write("                <input type=\"text\" name=\"name\" id=\"name\" placeholder=\"Gaurav Kumar\">\r\n");
      out.write("                <i class=\"fas fa-check-circle\"></i>\r\n");
      out.write("                <i class=\"fas fa-exclamation-circle\"></i>\r\n");
      out.write("                <small>Error Message</small>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-control \">\r\n");
      out.write("                <label for=\"\">Your Email</label>\r\n");
      out.write("                <input type=\"text\" name=\"email\" id=\"email\" placeholder=\"gaurav.kumar@gmail.com\">\r\n");
      out.write("                <i class=\"fas fa-check-circle\"></i>\r\n");
      out.write("                <i class=\"fas fa-exclamation-circle\"></i>\r\n");
      out.write("                <small>Error Message</small>\r\n");
      out.write("            </div>\r\n");
      out.write("             <div class=\"form-control\">\r\n");
      out.write("                <label for=\"\">Mobile Number</label>\r\n");
      out.write("                <input type=\"tel\" name=\"mno\" id=\"mno\" placeholder=\"9999999999\" onkeypress=\"return onlyNumberKey(event)\" maxlength=\"10\">\r\n");
      out.write("                <i class=\"fas fa-check-circle\"></i>\r\n");
      out.write("                <i class=\"fas fa-exclamation-circle\"></i>\r\n");
      out.write("                <small>Error Message</small>\r\n");
      out.write("            </div>\r\n");
      out.write("           <button onclick=\"checkInputs()\">Proceed To Pay</button>\r\n");
      out.write("           </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
