/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.97
 * Generated at: 2025-04-21 17:24:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <title>Flying Invite | Special Invite</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap core CSS -->\r\n");
      out.write("    <link href=\"vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Additional CSS Files -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./assets/css/fontawesome.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./assets/css/app.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./assets/css/animated.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./assets/css/owl.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./assets/css/style.css\">\r\n");
      out.write("    <link rel=\"icon\" href=\"/favicon.ico\" type=\"image/x-icon\"> <!-- ICO format -->\r\n");
      out.write("    <link rel=\"icon\" href=\"./images/flyinginvite.jpg\" type=\"image/jpg\"> <!-- PNG format -->\r\n");
      out.write("    <script async src=\"https://www.googletagmanager.com/gtag/js?id=G-DZ4MP44ET9\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("  window.dataLayer = window.dataLayer || [];\r\n");
      out.write("  function gtag(){dataLayer.push(arguments);}\r\n");
      out.write("  gtag('js', new Date());\r\n");
      out.write("\r\n");
      out.write("  gtag('config', 'G-DZ4MP44ET9');\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <!-- ***** Preloader Start ***** -->\r\n");
      out.write("  <div id=\"js-preloader\" class=\"js-preloader\">\r\n");
      out.write("    <div class=\"preloader-inner\">\r\n");
      out.write("      <span class=\"dot\"></span>\r\n");
      out.write("      <div class=\"dots\">\r\n");
      out.write("        <span></span>\r\n");
      out.write("        <span></span>\r\n");
      out.write("        <span></span>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- ***** Preloader End ***** -->\r\n");
      out.write("\r\n");
      out.write("  <!-- Pre-header Starts -->\r\n");
      out.write("  <div class=\"pre-header\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-lg-8 col-sm-8 col-7\">\r\n");
      out.write("          <ul class=\"info\">\r\n");
      out.write("            <li><a href=\"#\"><i class=\"fa fa-envelope\"></i>admin@flyinginvite.in</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-lg-4 col-sm-4 col-5\">\r\n");
      out.write("          <ul class=\"social-media\">\r\n");
      out.write("            <li><a href=\"https://www.facebook.com/profile.php?id=61567671551405\" target=\"_blank\"><i class=\"fa fa-facebook\"></i></a></li>\r\n");
      out.write("            <li><a href=\"#\"><i class=\"fa fa-google-plus\"></i></a></li>\r\n");
      out.write("            <li><a href=\"https://www.instagram.com/flyinginvite/?igsh=Yjh6aXM5eHZ3a3Nt\" target=\"_blank\"><i class=\"fa fa-instagram\"></i></a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- Pre-header End -->\r\n");
      out.write("\r\n");
      out.write("  <!-- ***** Header Area Start ***** -->\r\n");
      out.write("  <header class=\"header-area header-sticky wow slideInDown\" data-wow-duration=\"0.75s\" data-wow-delay=\"0s\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-12\">\r\n");
      out.write("          <nav class=\"main-nav\">\r\n");
      out.write("            <!-- ***** Logo Start ***** -->\r\n");
      out.write("            <a href=\"#\" class=\"logo\">\r\n");
      out.write("              <img src=\"assets/images/loggo.png\" style=\"width: 150px; margin-top:-30px;\" alt=\"\">\r\n");
      out.write("            </a>\r\n");
      out.write("            <!-- ***** Logo End ***** -->\r\n");
      out.write("            <!-- ***** Menu Start ***** -->\r\n");
      out.write("            <ul class=\"nav\">\r\n");
      out.write("              <li class=\"scroll-to-section\"><a href=\"#home\" class=\"active\">Home</a></li>\r\n");
      out.write("              <li class=\"scroll-to-section\"><a href=\"#about\">About</a></li>\r\n");
      out.write("              <li class=\"scroll-to-section\"><a href=\"#faq\">FAQ</a></li>\r\n");
      out.write("              <li class=\"scroll-to-section\"><a href=\"#services\">Services</a>  \r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"scroll-to-section\"><a href=\"terms_and_condition_page.jsp\" target=\"_blank\">Terms & Conditions</a></li>\r\n");
      out.write("              <li class=\"scroll-to-section\"><div class=\"border-first-button\"><a href=\"#contact\">Contact</a></div></li> \r\n");
      out.write("            </ul>        \r\n");
      out.write("            <a class='menu-trigger'>\r\n");
      out.write("                <span>Menu</span>\r\n");
      out.write("            </a>\r\n");
      out.write("            <!-- ***** Menu End ***** -->\r\n");
      out.write("          </nav>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </header>\r\n");
      out.write("  <!-- ***** Header Area End ***** -->\r\n");
      out.write("\r\n");
      out.write("  <div id=\"home\" class=\"main-banner wow fadeIn\" data-wow-duration=\"1s\" data-wow-delay=\"0.5s\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-lg-12\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-6 align-self-center\">\r\n");
      out.write("              <div class=\"left-content show-up header-text wow fadeInLeft\" data-wow-duration=\"1s\" data-wow-delay=\"1s\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                  <div class=\"col-lg-12\">\r\n");
      out.write("                    <h6>Flying Invite</h6>\r\n");
      out.write("                    <h2>India's  Interactive Invitation</h2>\r\n");
      out.write("                    <p>\r\n");
      out.write("                      Our main motive is to solve the problem of individual that they face while organizing event.\r\n");
      out.write("                      There is usually a challenge to get right count of attendees till the end of an event, This challenge leads to increase in cost for an individual.\r\n");
      out.write("                      Flying Invite addresses to this challenge by interacting with guest and track the count of attendees in real time in form of web template.\r\n");
      out.write("                    </p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"col-lg-12\">\r\n");
      out.write("                    <div class=\"border-first-button scroll-to-section\">\r\n");
      out.write("                      <a href=\"#contact\">Contact</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-6\">\r\n");
      out.write("              <div class=\"right-image wow fadeInRight\" data-wow-duration=\"1s\" data-wow-delay=\"0.5s\">\r\n");
      out.write("                <img src=\"assets/images/slider.png\" alt=\"\">\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div id=\"about\" class=\"about section\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-lg-12\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-6\">\r\n");
      out.write("              <div class=\"about-left-image  wow fadeInLeft\" data-wow-duration=\"1s\" data-wow-delay=\"0.5s\">\r\n");
      out.write("                <img src=\"assets/images/airplane.png\" alt=\"\">\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-6 align-self-center  wow fadeInRight\" data-wow-duration=\"1s\" data-wow-delay=\"0.5s\">\r\n");
      out.write("              <div class=\"about-right-content\">\r\n");
      out.write("                <div class=\"section-heading\">\r\n");
      out.write("                  <h6>About Us</h6>\r\n");
      out.write("                  <h4>Why Flying <em>Invite</em> ?</h4>\r\n");
      out.write("                  <div class=\"line-dec\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <p>Flying Invite mission is to transform the\r\n");
      out.write("                  way you invite your loved ones to lifes most\r\n");
      out.write("                  important moments. We provide a seamless and\r\n");
      out.write("                  eco-friendly way to send invitations for family, seasonal and corporate\r\n");
      out.write("                  events. Our beautifully designed digital\r\n");
      out.write("                  invitation web template combine creativity and convenience,\r\n");
      out.write("                  allowing you to make a lasting impression\r\n");
      out.write("                  without the hassle of traditional paper invites.\r\n");
      out.write("                  </p>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                  <div class=\"col-lg-4 col-sm-4\">\r\n");
      out.write("                    <div class=\"skill-item first-skill-item wow fadeIn\" data-wow-duration=\"1s\" data-wow-delay=\"0s\">\r\n");
      out.write("                      <div class=\"progress\" data-percentage=\"100\">\r\n");
      out.write("                        <span class=\"progress-left\">\r\n");
      out.write("                          <span class=\"progress-bar\"></span>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <span class=\"progress-right\">\r\n");
      out.write("                          <span class=\"progress-bar\"></span>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <div class=\"progress-value\">\r\n");
      out.write("                          <div>\r\n");
      out.write("                            100%<br>\r\n");
      out.write("                            <span>Eco-Friendly</span>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"col-lg-4 col-sm-4\">\r\n");
      out.write("                    <div class=\"skill-item second-skill-item wow fadeIn\" data-wow-duration=\"1s\" data-wow-delay=\"0s\">\r\n");
      out.write("                      <div class=\"progress\" data-percentage=\"100\">\r\n");
      out.write("                        <span class=\"progress-left\">\r\n");
      out.write("                          <span class=\"progress-bar\"></span>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <span class=\"progress-right\">\r\n");
      out.write("                          <span class=\"progress-bar\"></span>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <div class=\"progress-value\">\r\n");
      out.write("                          <div>\r\n");
      out.write("                            100%<br>\r\n");
      out.write("                            <span>Reliability</span>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"col-lg-4 col-sm-4\">\r\n");
      out.write("                    <div class=\"skill-item third-skill-item wow fadeIn\" data-wow-duration=\"1s\" data-wow-delay=\"0s\">\r\n");
      out.write("                      <div class=\"progress\" data-percentage=\"100\">\r\n");
      out.write("                        <span class=\"progress-left\">\r\n");
      out.write("                          <span class=\"progress-bar\"></span>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <span class=\"progress-right\">\r\n");
      out.write("                          <span class=\"progress-bar\"></span>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <div class=\"progress-value\">\r\n");
      out.write("                          <div>\r\n");
      out.write("                            100%<br>\r\n");
      out.write("                            <span>Availability</span>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div> \r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <div class=\"accordion-body\" id=\"faq\">\r\n");
      out.write("    <div class=\"accordion\">\r\n");
      out.write("      <div class=\"section-heading  wow fadeInDown\" data-wow-duration=\"1s\" data-wow-delay=\"0.5s\">\r\n");
      out.write("        <h6>FAQ</h6>\r\n");
      out.write("        <h4>Most Frequently <em>Asked</em> Questions</h4>\r\n");
      out.write("        <div class=\"line-dec\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"container\" style=\"margin-top: 80px;\">\r\n");
      out.write("        <div class=\"label\">What type of invitations we deliver ?</div>\r\n");
      out.write("        <div class=\"content\">We are providing invitations in form of web-template  for <strong> family events </strong> (i.e., wedding, birthday, annivarsary, baby shower) for <strong> corporate events </strong>(i.e., team-outing) <strong> other seasonal events </strong> (i.e., christmas, ganesh chaturthi, navratri, republic day, independance day, holi)</div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <hr>\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"label\">How much guest I can invite for my event ?</div>\r\n");
      out.write("        <div class=\"content\"> You can share invitation web-template url upto <strong> 1000 </strong> guest.</div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <hr>\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"label\">Can I able to track guest count ?</div>\r\n");
      out.write("        <div class=\"content\"><strong>Yes</strong>, you can able to track guest count going to attend your event.</div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <hr>\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"label\">What is the process to book an invitation ?</div>\r\n");
      out.write("        <div class=\"content\">Process is <strong> easy </strong>, You will contact to our admin team on given email address, admin will configure your template and will share you invitation web-template url on your contact, further you can share with your guest.</div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <hr>\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"label\">How much time will it take to deliver invitation ?</div>\r\n");
      out.write("        <div class=\"content\">Not more than <strong> 1 </strong> day.</div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <hr>\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"label\">Is it pocket friendly ?</div>\r\n");
      out.write("        <div class=\"content\"><strong>Yes</strong>, our invitation web-template's are pocket-friendly.</div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <hr>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"services\" class=\"services section\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-lg-12\">\r\n");
      out.write("            <div class=\"section-heading  wow fadeInDown\" data-wow-duration=\"1s\" data-wow-delay=\"0.5s\">\r\n");
      out.write("              <h6>Our Services</h6>\r\n");
      out.write("              <h4>Service <em>Types</em></h4>\r\n");
      out.write("              <div class=\"line-dec\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-lg-12\">\r\n");
      out.write("            <div class=\"naccs\">\r\n");
      out.write("              <div class=\"grid\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                  <div class=\"col-lg-12\">\r\n");
      out.write("                    <div class=\"menu\">\r\n");
      out.write("                      <div class=\"first-thumb active\">\r\n");
      out.write("                        <div class=\"thumb\">\r\n");
      out.write("                          <span class=\"icon\"><img src=\"assets/images/service-icon-04.png\" alt=\"\"></span>\r\n");
      out.write("                          Interactive Invitations\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div>\r\n");
      out.write("                        <div class=\"thumb\">                 \r\n");
      out.write("                          <span class=\"icon\"><img src=\"assets/images/service-icon-03.png\" alt=\"\"></span>\r\n");
      out.write("                           Birth Name Suggestion\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div>\r\n");
      out.write("                        <div class=\"thumb\">                 \r\n");
      out.write("                          <span class=\"icon\"><img src=\"assets/images/service-icon-04.png\" alt=\"\"></span>\r\n");
      out.write("                          Ukhane For Everyone\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div> \r\n");
      out.write("                  <div class=\"col-lg-12\">\r\n");
      out.write("                    <ul class=\"nacc\">\r\n");
      out.write("                      <li class=\"active\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                          <div class=\"thumb\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                              <div class=\"col-lg-6 align-self-center\">\r\n");
      out.write("                               \r\n");
      out.write("                              <div class=\"left-text\">\r\n");
      out.write("                                <h4 id=\"navigateHeader\">Interactive Invitations</h4>\r\n");
      out.write("                                <div class=\"navigate_section\">\r\n");
      out.write("                                  <h2 class=\"blink_me\" id=\"coming_soon_header\">Coming Soon</h2>\r\n");
      out.write("                                </div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <li>\r\n");
      out.write("                        <div>\r\n");
      out.write("                          <div class=\"thumb\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                              <div class=\"col-lg-6 align-self-center\">\r\n");
      out.write("                                <div class=\"left-text\">\r\n");
      out.write("                                  <h4 id=\"navigateHeader\">Birth Name Suggestor</h4>\r\n");
      out.write("                                  <div class=\"navigate_section\">\r\n");
      out.write("                                    <a  id=\"navigateBtn\" href=\"name_suggestor.jsp\">Know More</a>\r\n");
      out.write("                                  </div>         \r\n");
      out.write("                                </div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <li>\r\n");
      out.write("                        <div>\r\n");
      out.write("                          <div class=\"thumb\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                              <div class=\"col-lg-6 align-self-center\">\r\n");
      out.write("                                <div class=\"left-text\">\r\n");
      out.write("                                  <h4 id=\"navigateHeader\">Ukhane for Everyone</h4>\r\n");
      out.write("                                  <div class=\"navigate_section\">\r\n");
      out.write("                                    <a  id=\"navigateBtn\" href=\"entertainment.jsp\">Know More</a>\r\n");
      out.write("                                  </div>  \r\n");
      out.write("                                </div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <li>\r\n");
      out.write("                        <div>\r\n");
      out.write("                          <div class=\"thumb\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                              <div class=\"col-lg-6 align-self-center\">\r\n");
      out.write("                                <div class=\"left-text\">\r\n");
      out.write("                                  <h4>Seasonal Festival Invitation</h4>\r\n");
      out.write("                                  <p>A \"seasonal festival event\" is a celebration that occurs at a specific time of year.These events carry deep cultural meanings, including rituals, traditions, and special foods specific to the season.\r\n");
      out.write("                                    Flying Invite is providing basic baby shower template that you can share upto 1000 guests.\r\n");
      out.write("                                    Template is responsive on all device, interactive, time saving, cost effective, real time tracking of attendees count.\r\n");
      out.write("                                  </p>\r\n");
      out.write("                                  <div class=\"ticks-list\">\r\n");
      out.write("                                    <span><i class=\"fa fa-check\"></i> Web Template</span> <span><i class=\"fa fa-check\"></i> Basic Template</span> <span><i class=\"fa fa-check\"></i> Share upto 1000 guests</span>\r\n");
      out.write("                                    <span><i class=\"fa fa-check\"></i> Time Saving</span> <span><i class=\"fa fa-check\"></i> Less Cost</span> <span> <i class=\"fa fa-check\"></i> Real Time Tracking</span> <span> <i class=\"fa fa-check\"></i> Map Integration</span> <span> <i class=\"fa fa-check\"></i> Interactive</span>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <div class=\"col-lg-6 align-self-center\">\r\n");
      out.write("                                <div class=\"right-image\">\r\n");
      out.write("                                  <img src=\"assets/images/seasonal.png\" alt=\"\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </li>\r\n");
      out.write("                    \r\n");
      out.write("                    </ul>\r\n");
      out.write("                  </div>          \r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  <div id=\"contact\" class=\"contact-us section\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-lg-6 offset-lg-3\">\r\n");
      out.write("          <div class=\"section-heading wow fadeIn\" data-wow-duration=\"1s\" data-wow-delay=\"0.5s\" >\r\n");
      out.write("            <h6>Contact Us</h6>\r\n");
      out.write("            <h4>Get In Touch With Us <em>Now</em></h4>\r\n");
      out.write("            <div class=\"line-dec\"></div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-lg-12 wow fadeInUp\" data-wow-duration=\"0.5s\" data-wow-delay=\"0.25s\" >\r\n");
      out.write("          <form id=\"contact\" action=\"\" method=\"post\" >\r\n");
      out.write("            <div class=\"row\" >\r\n");
      out.write("              <div class=\"col-lg-12\" >\r\n");
      out.write("                <div class=\"contact-dec\" >\r\n");
      out.write("                  <img src=\"assets/images/contact-dec-v3.png\" alt=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-lg-7\" >\r\n");
      out.write("                <div class=\"fill-form\">\r\n");
      out.write("                  <div class=\"row\" >\r\n");
      out.write("                    <div class=\"col-lg-4\">\r\n");
      out.write("                      <div class=\"info-post\">\r\n");
      out.write("                        <div class=\"icon\">\r\n");
      out.write("                          <img src=\"assets/images/phone-icon.png\" alt=\"\"> <br>\r\n");
      out.write("                          <a href=\"#\">(+91) 8452043368</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4\">\r\n");
      out.write("                      <div class=\"info-post\">\r\n");
      out.write("                        <div class=\"icon\">\r\n");
      out.write("                          <img src=\"assets/images/email-icon.png\" alt=\"\"><br>\r\n");
      out.write("                          <a href=\"#\">admin@flyinginvite.in</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4\">\r\n");
      out.write("                      <div class=\"info-post\">\r\n");
      out.write("                        <div class=\"icon\">\r\n");
      out.write("                          <img src=\"assets/images/location-icon.png\" alt=\"\">\r\n");
      out.write("                          <a href=\"#\">Vaishnav Dhara, Plot no. 165, Sector No.4, New Panvel East, Maharashtra, India</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div> <br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3772.3827733322055!2d73.11647127373436!3d19.002847554267824!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3be7e90025ca1f13%3A0xddd377f79dc793c9!2sVaishanav%20Dhara%20appartment!5e0!3m2!1sen!2sin!4v1734084359207!5m2!1sen!2sin\" width=\"1050\" height=\"450\" style=\"border:0; width: 100%;\" allowfullscreen=\"\" loading=\"lazy\" referrerpolicy=\"no-referrer-when-downgrade\"></iframe>\r\n");
      out.write("\r\n");
      out.write("  <footer>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-lg-12\">\r\n");
      out.write("           <p>FlyingInvite@2025</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- Scripts -->\r\n");
      out.write("  <script src=\"./vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"./vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  <script src=\"./assets/js/owl-carousel.js\"></script>\r\n");
      out.write("  <script src=\"./assets/js/animation.js\"></script>\r\n");
      out.write("  <script src=\"./assets/js/imagesloaded.js\"></script>\r\n");
      out.write("  <script src=\"./assets/js/custom.js\"></script>\r\n");
      out.write("  <script src=\"./assets/js/app.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
