/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.97
 * Generated at: 2025-05-04 16:35:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class nameGenerator_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\r\n");
      out.write("          \"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Flying Invite | Child Name Generator</title>\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"./assets/css/style02.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write(" ");

    if(session.getAttribute("generatedOTP") == null){
	   response.sendRedirect("verifyEmail.jsp");
    }
 
 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div id=\"form-container\">\r\n");
      out.write("    \r\n");
      out.write("        <h2>Name Generator</h2>\r\n");
      out.write("        <form id=\"signup-form\" action=\"/FlyingInvite/NameGenerator\" method=\"POST\" onsubmit=\"return starting_letter_character_field_validation()\">\r\n");
      out.write("\r\n");
      out.write("            <label for=\"email\">It's a</label>\r\n");
      out.write("            <select id=\"selectGender\" name=\"child_gender_option\" required>\r\n");
      out.write("               <option>Boy</option>\r\n");
      out.write("               <option>Girl</option>\r\n");
      out.write("            </select>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"email\">Caste Preference</label>\r\n");
      out.write("             <div class=\"caste_preference\">\r\n");
      out.write("                <select id=\"castepref\" name=\"casteprefOpt\" onchange=\"caste_preference();\" required>\r\n");
      out.write("                    <option>Yes</option>\r\n");
      out.write("                    <option>No</option>\r\n");
      out.write("                 </select>\r\n");
      out.write("             </div>\r\n");
      out.write("\r\n");
      out.write("             <label for=\"email\" class=\"caste_preference\" id=\"lbl_caste_list_options\">Select Caste</label>\r\n");
      out.write("             <div class=\"caste_preference\" id=\"caste_list_options\">\r\n");
      out.write("                <select id=\"selectcaste\" name=\"selectcaste\" required>\r\n");
      out.write("                    <option>Hindu</option>\r\n");
      out.write("                    <option>Muslim</option>\r\n");
      out.write("                    <option>Christian</option>\r\n");
      out.write("                    <option>Sikh</option>\r\n");
      out.write("                 </select>\r\n");
      out.write("             </div>\r\n");
      out.write("\r\n");
      out.write("             <label for=\"email\">Starting Letter Preference</label>\r\n");
      out.write("             <div class=\"starting_letter_specific\" id=\"start_letter_pref\">\r\n");
      out.write("                <select id=\"starting_letter\" name=\"starting_letter_pref\" onchange=\"start_letter_preference();\" required>\r\n");
      out.write("                    <option>Yes</option>\r\n");
      out.write("                    <option>No</option>\r\n");
      out.write("                 </select>\r\n");
      out.write("             </div>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"email\" id=\"lbl_start_letter_list_options\">Starting Letter</label>\r\n");
      out.write("            <input type=\"text\" id=\"starting_letter_value\" name=\"starting_letter_value\" required><br><br>\r\n");
      out.write("            \r\n");
      out.write("            <button type=\"submit\">Download Name List</button>\r\n");
      out.write("        </form> <br>\r\n");
      out.write("        <div>\r\n");
      out.write("            <span>No Harm from our side, You can trust us.</span>\r\n");
      out.write("            <a href=\"verifyEmail.jsp\">Sign out</a> <br>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script src=\"./assets/js/script.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
