/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.97
 * Generated at: 2025-04-20 17:52:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class name_005fsuggestor_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("  <meta name=\"description\" content=\"\">\r\n");
      out.write("  <meta name=\"author\" content=\"\">\r\n");
      out.write("  <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("  <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <title>Flying Invite | Name Suggestor</title>\r\n");
      out.write("\r\n");
      out.write("  <!-- Bootstrap core CSS -->\r\n");
      out.write("  <link href=\"vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- Additional CSS Files -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"./assets/css/fontawesome.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"./assets/css/app.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"./assets/css/animated.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"./assets/css/owl.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"./assets/css/style.css\">\r\n");
      out.write("  \r\n");
      out.write("  <script async src=\"https://www.googletagmanager.com/gtag/js?id=G-DZ4MP44ET9\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("  window.dataLayer = window.dataLayer || [];\r\n");
      out.write("  function gtag(){dataLayer.push(arguments);}\r\n");
      out.write("  gtag('js', new Date());\r\n");
      out.write("\r\n");
      out.write("  gtag('config', 'G-DZ4MP44ET9');\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <!-- ***** Preloader Start ***** -->\r\n");
      out.write("  <div id=\"js-preloader\" class=\"js-preloader\">\r\n");
      out.write("    <div class=\"preloader-inner\">\r\n");
      out.write("      <span class=\"dot\"></span>\r\n");
      out.write("      <div class=\"dots\">\r\n");
      out.write("        <span></span>\r\n");
      out.write("        <span></span>\r\n");
      out.write("        <span></span>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- ***** Preloader End ***** -->\r\n");
      out.write("\r\n");
      out.write("  <!-- Pre-header Starts -->\r\n");
      out.write("  <div class=\"pre-header\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-lg-8 col-sm-8 col-7\">\r\n");
      out.write("          <ul class=\"info\">\r\n");
      out.write("            <li><a href=\"#\"><i class=\"fa fa-envelope\"></i>flyinginvite@gmail.com</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-lg-4 col-sm-4 col-5\">\r\n");
      out.write("          <ul class=\"social-media\">\r\n");
      out.write("            <li><a href=\"https://www.facebook.com/profile.php?id=61567671551405\" target=\"_blank\"><i class=\"fa fa-facebook\"></i></a></li>\r\n");
      out.write("            <li><a href=\"#\"><i class=\"fa fa-google-plus\"></i></a></li>\r\n");
      out.write("            <li><a href=\"https://www.instagram.com/flyinginvite/?igsh=Yjh6aXM5eHZ3a3Nt\" target=\"_blank\"><i class=\"fa fa-instagram\"></i></a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- Pre-header End -->\r\n");
      out.write("\r\n");
      out.write("  <div id=\"about\" class=\"about section\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-lg-12\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-6\">\r\n");
      out.write("              <div class=\"about-left-image  wow fadeInLeft\" data-wow-duration=\"1s\" data-wow-delay=\"0.5s\">\r\n");
      out.write("                <img src=\"assets/images/name_suggestor.png\" alt=\"mom with baby in her womb\">\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-6 align-self-center  wow fadeInRight\" data-wow-duration=\"1s\" data-wow-delay=\"0.5s\">\r\n");
      out.write("              <div class=\"about-right-content\">\r\n");
      out.write("                <div class=\"section-heading\">\r\n");
      out.write("                  <h6>Congratulations !</h6>\r\n");
      out.write("                  <h4>We have some <em>Name Suggestion</em></h4>\r\n");
      out.write("                  <div class=\"line-dec\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <p>\r\n");
      out.write("                    <ul><strong>We have some words</strong>\r\n");
      out.write("                      <li>Choosing your baby's name is one of the most heartfelt decisions you'll ever make and we're here to make it meaningful, joyful, and easy. Whether you're looking for something traditional, modern, spiritual, or unique, our application understands your vibe and offers names that resonate.\r\n");
      out.write("Let your baby's name be more than just letters let it carry dreams, stories, and love.\r\n");
      out.write("                      </li>\r\n");
      out.write("                    </ul> <br>\r\n");
      out.write("                </p>\r\n");
      out.write("              \r\n");
      out.write("              <a href=\"index.jsp\" class=\"btn btn-outline-danger\" role=\"button\"> Back</a>\r\n");
      out.write("              <a href=\"verifyEmail.jsp\" class=\"btn btn-outline-info\" role=\"button\">Generate</a>\r\n");
      out.write("              \r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <footer>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-lg-12\">\r\n");
      out.write("           <p>FlyingInvite@2025</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer>\r\n");
      out.write("\r\n");
      out.write("  <!-- Scripts -->\r\n");
      out.write("  <script src=\"./vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"./vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  <script src=\"./assets/js/owl-carousel.js\"></script>\r\n");
      out.write("  <script src=\"./assets/js/animation.js\"></script>\r\n");
      out.write("  <script src=\"./assets/js/imagesloaded.js\"></script>\r\n");
      out.write("  <script src=\"./assets/js/custom.js\"></script>\r\n");
      out.write("  <script src=\"./assets/js/app.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
