/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.97
 * Generated at: 2025-04-20 09:33:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class terms_005fand_005fcondition_005fpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("  <meta name=\"description\" content=\"\">\r\n");
      out.write("  <meta name=\"author\" content=\"\">\r\n");
      out.write("  <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("  <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <title>Flying Invite | Special Invite</title>\r\n");
      out.write("\r\n");
      out.write("  <!-- Bootstrap core CSS -->\r\n");
      out.write("  <link href=\"vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- Additional CSS Files -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"./assets/css/fontawesome.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"./assets/css/app.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"./assets/css/animated.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"./assets/css/owl.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"./assets/css/style.css\">\r\n");
      out.write("  \r\n");
      out.write("  <script async src=\"https://www.googletagmanager.com/gtag/js?id=G-DZ4MP44ET9\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("  window.dataLayer = window.dataLayer || [];\r\n");
      out.write("  function gtag(){dataLayer.push(arguments);}\r\n");
      out.write("  gtag('js', new Date());\r\n");
      out.write("\r\n");
      out.write("  gtag('config', 'G-DZ4MP44ET9');\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <!-- ***** Preloader Start ***** -->\r\n");
      out.write("  <div id=\"js-preloader\" class=\"js-preloader\">\r\n");
      out.write("    <div class=\"preloader-inner\">\r\n");
      out.write("      <span class=\"dot\"></span>\r\n");
      out.write("      <div class=\"dots\">\r\n");
      out.write("        <span></span>\r\n");
      out.write("        <span></span>\r\n");
      out.write("        <span></span>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- ***** Preloader End ***** -->\r\n");
      out.write("\r\n");
      out.write("  <!-- Pre-header Starts -->\r\n");
      out.write("  <div class=\"pre-header\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-lg-8 col-sm-8 col-7\">\r\n");
      out.write("          <ul class=\"info\">\r\n");
      out.write("            <li><a href=\"#\"><i class=\"fa fa-envelope\"></i>flyinginvite@gmail.com</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-lg-4 col-sm-4 col-5\">\r\n");
      out.write("          <ul class=\"social-media\">\r\n");
      out.write("            <li><a href=\"https://www.facebook.com/profile.php?id=61567671551405\" target=\"_blank\"><i class=\"fa fa-facebook\"></i></a></li>\r\n");
      out.write("            <li><a href=\"#\"><i class=\"fa fa-google-plus\"></i></a></li>\r\n");
      out.write("            <li><a href=\"https://www.instagram.com/flyinginvite/?igsh=Yjh6aXM5eHZ3a3Nt\" target=\"_blank\"><i class=\"fa fa-instagram\"></i></a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- Pre-header End -->\r\n");
      out.write("\r\n");
      out.write("  <div id=\"about\" class=\"about section\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-lg-12\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-6\">\r\n");
      out.write("              <div class=\"about-left-image  wow fadeInLeft\" data-wow-duration=\"1s\" data-wow-delay=\"0.5s\">\r\n");
      out.write("                <img src=\"assets/images/terms_condition.png\" alt=\"terms and condition image\">\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-6 align-self-center  wow fadeInRight\" data-wow-duration=\"1s\" data-wow-delay=\"0.5s\">\r\n");
      out.write("              <div class=\"about-right-content\">\r\n");
      out.write("                <div class=\"section-heading\">\r\n");
      out.write("                  <h6>Terms & Conditions</h6>\r\n");
      out.write("                  <h4>Thing's <em>You</em> Should Know</h4>\r\n");
      out.write("                  <div class=\"line-dec\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <p>\r\n");
      out.write("                  <div>\r\n");
      out.write("                     <span>Last Updated: Feb-02-2025</span>\r\n");
      out.write("                  </div> <br>\r\n");
      out.write("                    <ul><strong>Definitions</strong>\r\n");
      out.write("                      <li>User(s): Any individual or entity accessing or using the Website or Services.\r\n");
      out.write("                        Services: Digital invitation web template services, including but not limited to templates for weddings, birthdays, and other events, and related offerings.\r\n");
      out.write("                      </li>\r\n");
      out.write("                    </ul> <br>\r\n");
      out.write("                    <ul><strong>Eligibility to use the services</strong>\r\n");
      out.write("                      <li>You must be at least 18 years of age or have the legal capacity to enter into a binding contract under applicable laws in India.</li> \r\n");
      out.write("                    </ul> <br>\r\n");
      out.write("                    <ul><strong>License to use templates upon purchasing a template</strong>\r\n");
      out.write("                        <li>you are granted a limited, non-transferable, and non-exclusive license to use the digital invitation template for personal use only. You may not resell, redistribute, or use the templates for commercial purposes without prior written consent from Flying Invite.</li>\r\n");
      out.write("                    </ul> <br>\r\n");
      out.write("                    <ul><strong>Payment Terms</strong>\r\n");
      out.write("                        <li>1. All payments for templates or services are processed through secure payment gateways.</li>\r\n");
      out.write("                        <li>2. All charges are in INR <strong>(Indian Rupees)</strong>.</li>\r\n");
      out.write("                        <li>3. Payments are non-refundable unless specified otherwise.</li>\r\n");
      out.write("                    </ul> <br>\r\n");
      out.write("                    <ul> <strong>User-Generated Content</strong>\r\n");
      out.write("                      <li>You are solely responsible for any content you upload, share, or modify using our templates, including but not limited to text, images, and videos. You retain all ownership rights to the content you create, but grant [Your Company Name] a non-exclusive, worldwide, royalty-free license to use, display, and distribute the content as needed to provide the services.</li>\r\n");
      out.write("                    </ul> <br>\r\n");
      out.write("                    <ul><strong>Restrictions you agree not to</strong>\r\n");
      out.write("                        <li>1. Use the templates for illegal, harmful, or abusive activities.</li>\r\n");
      out.write("                        <li>2. Attempt to reverse-engineer, decompile, or disassemble any aspect of the website or services.</li>\r\n");
      out.write("                        <li>3. Engage in spamming, data scraping, or similar actions that could harm or disrupt the website.</li>\r\n");
      out.write("                    </ul> <br>\r\n");
      out.write("                    <ul><strong>Privacy and Data Protection</strong>\r\n");
      out.write("                        <li>Your use of the website is governed by our privacy policy, which outlines how we collect, use, and protect your personal data.</li>\r\n");
      out.write("                    </ul> <br>\r\n");
      out.write("                    <ul><strong>Limitation of Liability To the fullest extent permitted by law</strong>\r\n");
      out.write("                        <li>Flying Invite shall not be liable for any indirect, incidental, special, or consequential damages arising out of your use of the website or services, including any loss of data or profits.</li>\r\n");
      out.write("                    </ul> <br>\r\n");
      out.write("                    <ul><strong>Intellectual property rights</strong>\r\n");
      out.write("                       <li>Including trademarks, logos, and content on the Website, are owned by Flying Invite or its licensors. You may not use any of these without prior written consent.</li>\r\n");
      out.write("                    </ul> <br>\r\n");
      out.write("                    <ul> <strong>Indemnification You agree to indemnify and hold harmless Flying Invite</strong>\r\n");
      out.write("                      <li>Its affiliates, and employees from any claim, demand, or damage, including attorneyâs fees, arising out of your violation of these terms and conditions or misuse of the services.</li>\r\n");
      out.write("                    </ul> <br>\r\n");
      out.write("                    <ul><strong>Termination We reserve the right to suspend</strong>\r\n");
      out.write("                      <li>We have right to terminate your access to the Website and Services at our sole discretion if we believe you have violated these terms and conditions.</li>\r\n");
      out.write("                    </ul> <br>\r\n");
      out.write("                    <ul><strong>Modifications to Terms</strong>\r\n");
      out.write("                       <li>Flying Invite reserves the right to modify or update these Terms and Conditions at any time. You will be notified of such changes, and your continued use of the Website after such changes will constitute your acceptance of the modified terms.</li>\r\n");
      out.write("                    </ul> <br>\r\n");
      out.write("                    <ul><strong>Governing Law</strong>\r\n");
      out.write("                       <li>These Terms and Conditions shall be governed by and construed in accordance with the laws of India. Any disputes arising under or in connection with these terms shall be subject to the exclusive jurisdiction of the courts located in Navi Mumbai, India.</li>\r\n");
      out.write("                    </ul> <br>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                         <strong>Contact Information</strong>\r\n");
      out.write("                         <li>If you have any questions or concerns about these Terms and Conditions, please contact us at: <strong>flyinginvite@gmail.com</strong></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <footer>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-lg-12\">\r\n");
      out.write("           <p>FlyingInvite@2025</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer>\r\n");
      out.write("\r\n");
      out.write("  <!-- Scripts -->\r\n");
      out.write("  <script src=\"./vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"./vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  <script src=\"./assets/js/owl-carousel.js\"></script>\r\n");
      out.write("  <script src=\"./assets/js/animation.js\"></script>\r\n");
      out.write("  <script src=\"./assets/js/imagesloaded.js\"></script>\r\n");
      out.write("  <script src=\"./assets/js/custom.js\"></script>\r\n");
      out.write("  <script src=\"./assets/js/app.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
