/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.93
 * Generated at: 2024-12-04 14:53:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class edit_005fvenue_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Flying Invite | Edit Venue Information</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/styles.css\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Grey+Qo&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

     if(session.getAttribute("username") == null){
    	 response.sendRedirect("administrator.jsp");
     }

      out.write("\r\n");
      out.write("\r\n");

     Connection con;
     String driver = "com.mysql.cj.jdbc.Driver";
     String url = "jdbc:mysql://88.222.214.58:3306/flyinginvite_custom";
     String username = "root";
     String password = "13Viraj@2507";
     try{
    	 Class.forName(driver);
     }
     catch(Exception e){
    	 e.printStackTrace();
     }

      out.write("\r\n");
      out.write("	<nav class=\"navbar\">\r\n");
      out.write("		<div class=\"brand-loggo\">\r\n");
      out.write("			<h3 class=\"brand-name grey-qo-regular\">\r\n");
      out.write("				<a href=\"dashboard.jsp\">F I</a>\r\n");
      out.write("			</h3>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"menu-items\">\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li><a id=\"myaccount\" class=\"menu-disable\" href=\"javascript:submenu();\">\r\n");
      out.write("						<h3>");
      out.print( session.getAttribute("username") );
      out.write("</h3>\r\n");
      out.write("				</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>	\r\n");
      out.write("		<div id=\"submenu_list_option\" class=\"nav-sub-list\">\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li><a href=\"administrator.jsp\">Log Out</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>	\r\n");
      out.write("\r\n");
      out.write("	<section>\r\n");
      out.write("		<div class=\"input-field form_heading\">\r\n");
      out.write("			<h1>Edit Venue <br> Information</h1>		\r\n");
      out.write("			<a href=\"venue_info.jsp\" style=\"color:white; margin-left:180px;\">Back</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"section-filter-container\" style=\"width:300px;\">\r\n");
      out.write("			<div class=\"add_credentials_container\">\r\n");
      out.write("				<form class=\"f1\" autocomplete=\"off\" action=\"editVenueInfo\"\r\n");
      out.write("					method=\"post\" onSubmit=\"return validate3();\">\r\n");
      out.write("					<div class=\"input-field\">\r\n");
      out.write("						<label class=\"lbl\">Select User</label>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"inputfield\">\r\n");
      out.write("					");

					try{
			    	 con = DriverManager.getConnection(url, username, password);
			         PreparedStatement ps = con.prepareStatement("select * from user_info Order By userId Desc");
			         ResultSet rs = ps.executeQuery();
			         
					
      out.write("\r\n");
      out.write("						<select style=\"width:100%; padding: 10px;\" name=\"user_id\" required>\r\n");
      out.write("						   ");
while(rs.next()){ 
      out.write("\r\n");
      out.write("							<option value=\"");
      out.print( rs.getInt("userId") );
      out.write('"');
      out.write('>');
      out.print( rs.getInt("userId") );
      out.write("</option>\r\n");
      out.write("							");
 } 
      out.write("\r\n");
      out.write("						</select>\r\n");
      out.write("					</div>\r\n");
      out.write("				    ");

                         }
                          catch(Exception e){
    	                    e.printStackTrace();
                         }
                     
      out.write("\r\n");
      out.write("                     \r\n");
      out.write("                    <div class=\"input-field\">\r\n");
      out.write("						<label class=\"lbl\">Select Venue</label>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("	             <div class=\"inputfield\">\r\n");
      out.write("					");

					try{
			    	 con = DriverManager.getConnection(url, username, password);
			         PreparedStatement ps = con.prepareStatement("select venue_id from venue_info Order By venue_id Desc");
			         ResultSet rs = ps.executeQuery();
			         
					
      out.write("\r\n");
      out.write("						<select style=\"width:100%; padding: 10px;\" name=\"venue_id\">\r\n");
      out.write("						   ");
while(rs.next()){ 
      out.write("\r\n");
      out.write("							<option value=\"");
      out.print( rs.getInt("venue_id") );
      out.write('"');
      out.write('>');
      out.print( rs.getInt("venue_id") );
      out.write("</option>\r\n");
      out.write("							");
 } 
      out.write("\r\n");
      out.write("						</select>\r\n");
      out.write("					</div>\r\n");
      out.write("				    ");

                         }
                          catch(Exception e){
    	                    e.printStackTrace();
                         }
                     
      out.write("\r\n");
      out.write("                     \r\n");
      out.write("					<div class=\"input-field\">\r\n");
      out.write("						<label class=\"lbl\">Enter Venue</label>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"inputfield\">\r\n");
      out.write("						<textarea style=\"width:150%; padding: 30px; font-size: 20px;\" name=\"venue_info\"  placeholder=\"venue\" required></textarea>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"formSubmit\">\r\n");
      out.write("						<input type=\"submit\" value=\"EDIT VENUE\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("    </section>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"./js/index.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
