/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.97
 * Generated at: 2025-03-23 14:28:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class view_005frecords_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>View All Records</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/styles.css\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Grey+Qo&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("      ");

       if(session.getAttribute("username") == null){
    	   response.sendRedirect("administrator.jsp");
       }
    
      out.write("\r\n");
      out.write("        ");

        String driver = "com.mysql.cj.jdbc.Driver";
        String url = "jdbc:mysql://88.222.214.58:3306/flyinginvite_custom";
        String username = "root";
        String password = "13Viraj@2507";
        ResultSet rs = null;
        Connection con = null;
        PreparedStatement ps = null;
        try{
        	Class.forName(driver);
        	con = DriverManager.getConnection(url,username,password);
        	ps= con.prepareStatement("select * from user_info Inner Join venue_info using(userId) inner join template_info using(userId) inner join page_info using(userId) inner join event_info using(venue_id)");
            rs = ps.executeQuery();
    
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    	<nav class=\"navbar\">\r\n");
      out.write("		<div class=\"brand-loggo\">\r\n");
      out.write("			<h3 class=\"brand-name grey-qo-regular\">\r\n");
      out.write("				<a href=\"dashboard.jsp\">F I</a>\r\n");
      out.write("			</h3>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"menu-items\">\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li><a id=\"myaccount\" class=\"menu-disable\" href=\"javascript:submenu();\">\r\n");
      out.write("						<h3>");
      out.print( session.getAttribute("username") );
      out.write("</h3>\r\n");
      out.write("				</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>	\r\n");
      out.write("		<div id=\"submenu_list_option\" class=\"nav-sub-list\">\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li><a href=\"administrator.jsp\">Log Out</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>	\r\n");
      out.write("	\r\n");
      out.write("	    <section>\r\n");
      out.write("		<div class=\"input-field form_heading\" style=\"width:130%\">\r\n");
      out.write("			<h1 style=\"margin-left:-310px;font-size:16px; color:white;\">View All Records</h1>\r\n");
      out.write("		    <span><a href=\"dashboard.jsp\" style=\"color:white; margin-left:890px; font-size:14px;\"> Back</a></span>\r\n");
      out.write("		</div>\r\n");
      out.write("		      <div class=\"container1\">\r\n");
      out.write("		          <table style=\"margin: 20px -350px; padding:20px; font-size:12px;\">\r\n");
      out.write("                         <thead style=\"background-color:#2C3E50;\">\r\n");
      out.write("                            <tr>\r\n");
      out.write("                               <td style=\"padding: 20px; border:1px solid black; color:white;\">userId</td>\r\n");
      out.write("                               <td style=\"padding: 20px; border:1px solid black; color:white;\">firstname</td>\r\n");
      out.write("                               <td style=\"padding: 20px; border:1px solid black; color:white;\">lastname</td> \r\n");
      out.write("                               <td style=\"padding: 20px; border:1px solid black; color:white;\">event_id</td>\r\n");
      out.write("                               <td style=\"padding: 20px; border:1px solid black; color:white;\">event_date</td>\r\n");
      out.write("                               <td style=\"padding: 20px; border:1px solid black; color:white;\">event_from</td>\r\n");
      out.write("                               <td style=\"padding: 20px; border:1px solid black; color:white;\">event_to</td>\r\n");
      out.write("                               <td style=\"padding: 20px; border:1px solid black; color:white;\">venue_id</td>\r\n");
      out.write("                               <td style=\"padding: 20px; border:1px solid black; color:white;\">template_id</td>\r\n");
      out.write("                               <td style=\"padding: 20px; border:1px solid black; color:white;\">template_type</td>\r\n");
      out.write("                               <td style=\"padding: 20px; border:1px solid black; color:white;\">page_id</td>\r\n");
      out.write("                               <td style=\"padding: 20px; border:1px solid black; color:white;\">Remove</td>\r\n");
      out.write("                           </tr>\r\n");
      out.write("                        </thead>\r\n");
      out.write("                   <tbody style=\"background-color:#7FA1C3;\">\r\n");
      out.write("                  ");

                     while(rs.next()){
                   
      out.write(" \r\n");
      out.write("                    <tr>\r\n");
      out.write("                   <td style=\"padding: 20px; border:1px solid black;\">");
      out.print( rs.getInt("userId") );
      out.write("</td>\r\n");
      out.write("                   <td style=\"padding: 20px; border:1px solid black;\">");
      out.print( rs.getString("user_firstname") );
      out.write("</td>\r\n");
      out.write("                   <td style=\"padding: 20px; border:1px solid black;\">");
      out.print( rs.getString("user_lastname") );
      out.write("</td>\r\n");
      out.write("                   <td style=\"padding: 20px; border:1px solid black;\">");
      out.print( rs.getInt("event_id") );
      out.write("</td>\r\n");
      out.write("                   <td style=\"padding: 20px; border:1px solid black;\">");
      out.print( rs.getString("event_date") );
      out.write("</td>\r\n");
      out.write("                   <td style=\"padding: 20px; border:1px solid black;\">");
      out.print( rs.getString("event_from") );
      out.write("</td>\r\n");
      out.write("                   <td style=\"padding: 20px; border:1px solid black;\">");
      out.print( rs.getString("event_to") );
      out.write("</td>\r\n");
      out.write("                   <td style=\"padding: 20px; border:1px solid black;\">");
      out.print( rs.getInt("venue_id") );
      out.write("</td>\r\n");
      out.write("                   <td style=\"padding: 20px; border:1px solid black;\">");
      out.print( rs.getInt("template_id") );
      out.write("</td>\r\n");
      out.write("                   <td style=\"padding: 20px; border:1px solid black;\">");
      out.print( rs.getString("template_type") );
      out.write("</td>\r\n");
      out.write("                   <td style=\"padding: 20px; border:1px solid black;\">");
      out.print( rs.getString("page_id") );
      out.write("</td>\r\n");
      out.write("                   <td style=\"padding: 20px; border:1px solid; cursor:pointer;\"><a href=\"removeDetail?userId=");
      out.print(rs.getInt("userId"));
      out.write("&venue_id=");
      out.print( rs.getInt("venue_id"));
      out.write("&template_id=");
      out.print( rs.getInt("template_id"));
      out.write("&page_id=");
      out.print(rs.getInt("page_id"));
      out.write("&event_id=");
      out.print( rs.getInt("event_id"));
      out.write("\"><i class=\"material-icons\" style=\"color:red;\">delete</i></a></td>\r\n");
      out.write("                   </tr>\r\n");
      out.write("                   ");

                     }
                   
      out.write("\r\n");
      out.write("                   </tbody>\r\n");
      out.write("               </table>\r\n");
      out.write("		      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    \r\n");
      out.write("     ");

                   
        }
        catch(Exception e){
        	e.printStackTrace();
        }
        finally {
            // Close resources
            try { 
            	if (rs != null) 
            		rs.close(); 
            	if (ps != null) 
            		ps.close(); 
            	if (con != null) 
            		con.close(); 
            	} 
            catch (SQLException e) { 
            	e.printStackTrace();
            }
        }
 

      out.write("\r\n");
      out.write("	<script type=\"text/javascript\" src=\"./js/index.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
